const { Router } = require('./utils/Router')
const { WebApp } = require('./utils/WebApp')
const constants = require('./utils/constants')
const { index } = require('./routes')
const { login } = require('./routes/login')
const { addProduct } = require('./routes/addproductPage')
const { myAccount } = require('./routes/myaccount')
const { search } = require('./routes/search')
const { admin } = require('./routes/admin-product')
const { docs } = require('./routes/docs')
const { updateProduct } = require('./routes/updateProduct')
const { addMakeup } = require('./routes/addmakeup')
const { updateMakeup } = require('./routes/updateMakeup')
const { adminHome } = require('./routes/admin-home')
const { adminFeedback } = require('./routes/admin-feedback')
const { adminMakeup } = require('./routes/admin-makeup')
const userRouter = require("./routes/users")
const productRouter = require("./routes/products")
const { searchMakeup } = require('./routes/searchMakeup')
const feedbackRouter = require("./routes/feedbacks")
const makeupRouter = require("./routes/makeup")
require("./server-conn");
const router = new Router()
router.use('', index)
router.use('', login)
router.use('', myAccount)
router.use('', search)
router.use('',addProduct)
router.use('',admin)
router.use('',updateProduct)
router.use('',docs)
router.use('',makeupRouter)
router.use('',userRouter)
router.use('',productRouter)
router.use('',addMakeup)
router.use('',updateMakeup)
router.use('',adminHome)
router.use('',adminFeedback)
router.use('',adminMakeup)
router.use('',searchMakeup)
router.use('',feedbackRouter)
console.log(router)
const app = new WebApp(constants.port, router)
app.listen()

console.log()
